# -*- coding: utf-8 -*-
"""AI/ML p1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13QHQF5lL5jbR-W9yJoXnW3I1ry_QdBi5

**1 HELLO WORLD**
"""

print("Hello World")

"""**2 ARTHMETIC OPERATIONS**"""

inp1 = int(input("Enter number 1: "))
inp2 = int(input("Enter number 2: "))

add = inp1 + inp2
print("Addition of two numbers is " + str(add))

inp1 = int(input("Enter number 1: "))
inp2 = int(input("Enter number 2: "))

sub = inp1 - inp2
print("Subtraction of two numbers is " + str(sub))

inp1 = int(input("Enter number 1: "))
inp2 = int(input("Enter number 2: "))

mul = inp1 * inp2
print("Multiplication of two numbers is " + str(mul))

inp1 = int(input("Enter number 1: "))
inp2 = int(input("Enter number 2: "))

div = inp1 / inp2
print("Division of two numbers is " + str(div))

"""**3 AREA OF CIRCLE**"""

import math
radius = int(input("Enter radius for circle: "))
areaOfCircle = math.pi * radius * radius
print("Area of Circle is ",areaOfCircle)

"""**4 AREA OF TRIANGLE**"""

b = int(input("Enter breadth for triangle: "))
h = int(input("Enter height for triangle: "))

areaOfTriangle = 0.5 * b * h
print("Area of Triangle is ",areaOfTriangle)

"""**5 GENERATE EVEN TERMS**"""

evenTerms = int(input(""))
print("Following are the even terms from 0 to", str(evenTerms))
for i in range((evenTerms*2)+1):
  if(i%2)==0:
    print(i)

"""**6 GENERATE ODD TERMS**"""

oddTerms = int(input())
print("Following are the odd terms from 0 to", str(oddTerms))
for i in range((oddTerms*2)+1):
  if(i%2)!=0:
    print(i)

"""**7 GENERATE MULTIPLICATION TABLE USING LOOPS**"""

print("Multiplication Table:")
tableToPrint = int(input("Enter number "))
for i in range(11):
  print(str(tableToPrint) + " x " + str(i) + " = " + str(i * tableToPrint))

"""**8 TYPES OF LOOPS**

**WHILE LOOP**
"""

num_of_times = 1

while num_of_times <= 7:
  print("Narender Keswani")
  num_of_times += 1

"""**9 PYRAMID**"""

rows = int(input("Enter number of rows: "))

for i in range(rows):
    for j in range(i+1):
        print("Narender ", end="")
    print("\n")

"""**10 PRIME NUMBER CHECK**"""

num = int(input("Enter a number: "))

flag = False

if num > 1:
    for i in range(2, num):
        if (num % i) == 0:
            flag = True
            break

if flag:
    print(num, "is not a prime number")
else:
    print(num, "is a prime number")

"""**11 GENERATE PRIME NUMBERS**"""

lower_value = int(input ("Please, Enter the Lowest Range Value: "))  
upper_value = int(input ("Please, Enter the Upper Range Value: "))  
  
print ("The Prime Numbers in the range are: ")  
for number in range (lower_value, upper_value + 1):  
    if number > 1:  
        for i in range (2, number):  
            if (number % i) == 0:  
                break  
        else:  
            print (number)

"""**12 PALINDROME NUMBER CHECK**"""

def isPalindrome(s):
	return s == s[::-1]

s = "malayalam"
ans = isPalindrome(s)

if ans:
	print("Yes")
else:
	print("No")

"""**13 TAKE INPUT FROM USER (ROLL, NAME, DOB,ADDRESS) AND STORE IN ARRAY DATATYPE**"""

roll = int(input("Enter roll "))
name = input("Enter name ")
dob = input("Enter dob ")
address = input("Enter address ")

thisdict = {
  "roll": roll,
  "name": name,
  "dob": dob,
  "address":address
}

for x, y in thisdict.items():
  print("The value of ",x, "is ", y)